# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'neural_network_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(670, 700)
        MainWindow.setStyleSheet("background-color: #FFC567\n"
"")
        self.widget = QtWidgets.QWidget(MainWindow)
        self.widget.setStyleSheet("QSpinBox{\n"
"    border: 2px solid rgb(48, 25, 106);\n"
"    padding: 10px 20px;\n"
"    border-radius: 5px;  \n"
"    color: rgb(48, 25, 106);\n"
"    background-color:#fd5a46;\n"
"    font-size: 16pt;\n"
"}\n"
"\n"
"QLabel{\n"
"    color: rgb(48, 25, 106);\n"
"    font-size: 16pt;\n"
"}\n"
"\n"
"QComboBox{\n"
"    border: 2px solid rgb(48, 25, 106);\n"
"    padding: 10px 20px;\n"
"    border-radius: 5px;  \n"
"    color: rgb(48, 25, 106);\n"
"    background-color:#fd5a46;\n"
"    font-size: 16pt;\n"
"}\n"
"\n"
"QPushButton{\n"
"    border: 2px solid rgb(48, 25, 106);\n"
"    padding: 10px 20px;\n"
"    border-radius: 5px;  \n"
"    color: rgb(48, 25, 106);\n"
"    background-color:#fd5a46;\n"
"    font-size: 16pt;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(253, 66, 49);\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ListViewNeuralNetworkLayers = QtWidgets.QListView(self.widget)
        self.ListViewNeuralNetworkLayers.setStyleSheet("QListView{\n"
"    border: 2px solid rgb(48, 25, 106);\n"
"    padding: 10px 20px;\n"
"    border-radius: 5px;  \n"
"    color: rgb(48, 25, 106);\n"
"    background-color:#fd5a46;\n"
"    font-size: 16pt;\n"
"}")
        self.ListViewNeuralNetworkLayers.setObjectName("ListViewNeuralNetworkLayers")
        self.horizontalLayout.addWidget(self.ListViewNeuralNetworkLayers)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ButtonAdd = QtWidgets.QPushButton(self.widget)
        self.ButtonAdd.setObjectName("ButtonAdd")
        self.verticalLayout_2.addWidget(self.ButtonAdd)
        self.ButtonDelete = QtWidgets.QPushButton(self.widget)
        self.ButtonDelete.setObjectName("ButtonDelete")
        self.verticalLayout_2.addWidget(self.ButtonDelete)
        self.LabelNeuronCount = QtWidgets.QLabel(self.widget)
        self.LabelNeuronCount.setObjectName("LabelNeuronCount")
        self.verticalLayout_2.addWidget(self.LabelNeuronCount)
        self.SpinBoxNeuronCount = QtWidgets.QSpinBox(self.widget)
        self.SpinBoxNeuronCount.setObjectName("SpinBoxNeuronCount")
        self.verticalLayout_2.addWidget(self.SpinBoxNeuronCount)
        self.LabelActivationFunction = QtWidgets.QLabel(self.widget)
        self.LabelActivationFunction.setObjectName("LabelActivationFunction")
        self.verticalLayout_2.addWidget(self.LabelActivationFunction)
        self.ComboBoxTypeOfActivationFunction = QtWidgets.QComboBox(self.widget)
        self.ComboBoxTypeOfActivationFunction.setObjectName("ComboBoxTypeOfActivationFunction")
        self.verticalLayout_2.addWidget(self.ComboBoxTypeOfActivationFunction)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.LabelBatchSize = QtWidgets.QLabel(self.widget)
        self.LabelBatchSize.setObjectName("LabelBatchSize")
        self.verticalLayout_3.addWidget(self.LabelBatchSize)
        self.SpinBoxBatchSize = QtWidgets.QSpinBox(self.widget)
        self.SpinBoxBatchSize.setObjectName("SpinBoxBatchSize")
        self.verticalLayout_3.addWidget(self.SpinBoxBatchSize)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.LabelEpochCount = QtWidgets.QLabel(self.widget)
        self.LabelEpochCount.setObjectName("LabelEpochCount")
        self.verticalLayout_4.addWidget(self.LabelEpochCount)
        self.SpinBoxEpochCount = QtWidgets.QSpinBox(self.widget)
        self.SpinBoxEpochCount.setObjectName("SpinBoxEpochCount")
        self.verticalLayout_4.addWidget(self.SpinBoxEpochCount)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.ButtonStartTraining = QtWidgets.QPushButton(self.widget)
        self.ButtonStartTraining.setStyleSheet("QPushButton{\n"
"    border: 2px solid rgb(48, 25, 106);\n"
"    padding: 10px 20px;\n"
"    border-radius: 5px;  \n"
"    color: rgb(48, 25, 106);\n"
"    background-color:#fd5a46;\n"
"    font-size: 16pt;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color:rgb(253, 66, 49);\n"
"}")
        self.ButtonStartTraining.setFlat(False)
        self.ButtonStartTraining.setObjectName("ButtonStartTraining")
        self.verticalLayout.addWidget(self.ButtonStartTraining)
        MainWindow.setCentralWidget(self.widget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Настройка нейронной сети"))
        self.ButtonAdd.setText(_translate("MainWindow", "Добавить"))
        self.ButtonDelete.setText(_translate("MainWindow", "Удалить"))
        self.LabelNeuronCount.setText(_translate("MainWindow", "Выберите количество нейронов"))
        self.LabelActivationFunction.setText(_translate("MainWindow", "Выберите функцию активации"))
        self.LabelBatchSize.setText(_translate("MainWindow", "Выберите размер батча"))
        self.LabelEpochCount.setText(_translate("MainWindow", "Выберите количество эпох"))
        self.ButtonStartTraining.setText(_translate("MainWindow", "Начать обучение"))



